
/**
 * Temporary static data
 * Later replace with database API
 */

//services/ → handles fetching, mock data, API calls, business logic

//services/assignedDeviceService.ts

import { AssignedDevice } from "@/models/AssignedDevice";

// ✅ ADD THIS FUNCTION
export const getAssignedDevicesByEmployee = async (employeeId: string) => {
    return assignedDevices.filter(
        (item) => item.employeeId === employeeId
    );
};

export const assignedDevices: AssignedDevice[] = [
    {
        sl: 1,
        referenceNumber: "14451",
        mrnNumber: "MR-2025-001",
        prNumber: "PR-2025-001",
        employeeId: "EMP011",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Manager",
        department: "IP Trasmission",
        category: "Laptop",
        deviceSl: "nosn54643d",
        model: "OP-620A",
        deviceType: "Permanent",
        status: "Available",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "ruhul",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Assigned in Permanently",
    },

    {
        sl: 2,
        referenceNumber: "14452",
        mrnNumber: "MR-2025-002",
        prNumber: "PR-2025-002",
        employeeId: "EMP012",
        employeeName: "Md. Tauhid Ali",
        designation: "AGM",
        department: "SCM",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620B",
        deviceType: "Permanent",
        status: "Transferred",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "ruhul",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "DeviceTransferred in Permanent",
    },
    {
        sl: 3,
        referenceNumber: "14453",
        mrnNumber: "MR-2025-003",
        prNumber: "PR-2025-003",
        employeeId: "EMP017",
        employeeName: "Jamil Ali",
        designation: "GM",
        department: "DWD",
        category: "RAM",
        deviceSl: "nosn54643d",
        model: "OP-620C",
        deviceType: "Permanent",
        status: "Returned",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "ruhul",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Returned in good condition",
    },

    {
        sl: 4,
        referenceNumber: "14454",
        mrnNumber: "MR-2025-004",
        prNumber: "PR-2025-004",
        employeeId: "EMP022",
        employeeName: "Md. Manik Mia",
        designation: "Sr GM",
        department: "Chairman Secretariat",
        category: "Laptop-LC2",
        deviceSl: "nosn54643d",
        model: "OP-620D",
        deviceType: "Permanent",
        status: "Returned",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Returned in good condition",
    },
    {
        sl: 5,
        referenceNumber: "14455",
        mrnNumber: "MR-2025-005",
        prNumber: "PR-2025-005",
        employeeId: "EMP017",
        employeeName: "Jamil Ali",
        designation: "GM",
        department: "DWD",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620E",
        deviceType: "Permanent",
        status: "Expired",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Stored in good condition",
    },
    {
        sl: 6,
        referenceNumber: "14456",
        mrnNumber: "MR-2025-006",
        prNumber: "PR-2025-006",
        employeeId: "EMP018",
        employeeName: "Md. Nzimul Islam",
        designation: "CTO",
        department: "Software",
        category: "Monitor",
        deviceSl: "nosn54643d",
        model: "OP-620F",
        deviceType: "Permanent",
        status: "Transferred",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Transferred in Permanently",
    },
    {
        sl: 7,
        referenceNumber: "14457",
        mrnNumber: "MR-2025-007",
        prNumber: "PR-2025-007",
        employeeId: "EMP019",
        employeeName: "Md. Jamil Uddin",
        designation: "Sr Manager",
        department: "Technology and Operations",
        category: "Laptop-LC1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Transferred",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Transferred in Permanently",
    },

    {
        sl: 8,
        referenceNumber: "14458",
        mrnNumber: "MR-2025-008",
        prNumber: "PR-2025-008",
        employeeId: "EMP020",
        employeeName: "Md. Zaman Ali",
        designation: "Manager",
        department: "Technology and Operations",
        category: "Laptop-LC3",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Assigned",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Assigned in good condition",
    },

    {
        sl: 9,
        referenceNumber: "14459",
        mrnNumber: "MR-2025-009",
        prNumber: "PR-2025-009",
        employeeId: "EMP018",
        employeeName: "Md. Nzimul Islam",
        designation: "CTO",
        department: "Software",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Assigned",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Assigned in Permanently",
    },
    {
        sl: 10,
        referenceNumber: "14460",
        mrnNumber: "MR-2025-010",
        prNumber: "PR-2025-010",
        employeeId: "EMP021",
        employeeName: "Md. Zobayar Ali",
        designation: "Assitant Manager",
        department: "Admin",
        category: "Printer",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Assigned",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Device Assigned in Permanently",
    },

    {
        sl: 11,
        referenceNumber: "14461",
        mrnNumber: "MR-2025-011",
        prNumber: "PR-2025-011",
        employeeId: "EMP021",
        employeeName: "Md. Zobayar Ali",
        designation: "Assitant Manager",
        department: "Admin",
        category: "Laptop-LC1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Stored",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Now Available in Stock",
    },
    {
        sl: 12,
        referenceNumber: "14462",
        mrnNumber: "MR-2025-012",
        prNumber: "PR-2025-012",
        employeeId: "EMP021",
        employeeName: "Md. Zobayar Ali",
        designation: "Assitant Manager",
        department: "Admin",
        category: "Laptop-LC2",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Damaged",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Now Available in Stock",
    },
    {
        sl: 13,
        referenceNumber: "14463",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP021",
        employeeName: "Md. Zobayar Ali",
        designation: "Assitant Manager",
        department: "Admin",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Available",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Now Available in Stock",
    },

    {
        sl: 14,
        referenceNumber: "14464",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP016",
        employeeName: "Shakil Akhter Khan",
        designation: "DGM",
        department: "IT",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Available",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Now Available in Stock",
    },


    {
        sl: 15,
        referenceNumber: "14465",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP015",
        employeeName: "Md. Saulad Zahir Alv",
        designation: "Manager",
        department: "IT",
        category: "Laptop LC-2",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Claimed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Claimed",
    },


    {
        sl: 16,
        referenceNumber: "14466",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP015",
        employeeName: "Md. Saulad Zahir Alv",
        designation: "Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "To Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Vendor Transferred",
    },

    {
        sl: 17,
        referenceNumber: "14467",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Kabir Uddin",
        designation: "Sr. Manager",
        department: "HR",
        category: "House",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Recovered",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Recovered",
    },

    {
        sl: 18,
        referenceNumber: "14468",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Kabir Uddin",
        designation: "Sr. Manager",
        department: "HR",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Expired",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Expired",
    },


    {
        sl: 19,
        referenceNumber: "14469",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Kabir Uddin",
        designation: "Sr. Manager",
        department: "HR",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Service Requrest",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },


    {
        sl: 20,
        referenceNumber: "14470",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP013",
        employeeName: "Rustom Ali",
        designation: "Assitant Manager",
        department: "IT",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Service Requrest",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 21,
        referenceNumber: "14471",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP013",
        employeeName: "Rustom Ali",
        designation: "Assitant Manager",
        department: "IT",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "In Progress",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },


    {
        sl: 22,
        referenceNumber: "14472",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP013",
        employeeName: "Rustom Ali",
        designation: "Assitant Manager",
        department: "IT",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "In Progress",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 23,
        referenceNumber: "14473",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP013",
        employeeName: "Rustom Ali",
        designation: "Assitant Manager",
        department: "IT",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Closed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 24,
        referenceNumber: "14474",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP012",
        employeeName: "Md. Tauhid Ali",
        designation: "AGM",
        department: "SCM",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Closed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 25,
        referenceNumber: "14475",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP012",
        employeeName: "Md. Tauhid Ali",
        designation: "AGM",
        department: "SCM",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Closed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },
    {
        sl: 26,
        referenceNumber: "14475",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP023",
        employeeName: "Muhsina Akter",
        designation: "Assitant Manager",
        department: "Software",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Lost",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 27,
        referenceNumber: "14476",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP014",
        employeeName: "Nur Hossen",
        designation: "Assitant Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Lost",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 28,
        referenceNumber: "14477",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP014",
        employeeName: "Nur Hossen",
        designation: "Assitant Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Ownership",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },
    {
        sl: 29,
        referenceNumber: "14478",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP014",
        employeeName: "Nur Hossen",
        designation: "Assitant Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Ownership",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 30,
        referenceNumber: "14479",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP014",
        employeeName: "Nur Hossen",
        designation: "Assitant Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Recovered",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 31,
        referenceNumber: "14480",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP014",
        employeeName: "Nur Hossen",
        designation: "Assitant Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "To Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },

    {
        sl: 32,
        referenceNumber: "14481",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP011",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Manager",
        department: "IP Trasmission",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "To Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Today is open",
    },


    {
        sl: 33,
        referenceNumber: "14482",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP022",
        employeeName: "Md. Manik Mia",
        designation: "Sr GM",
        department: "Chairman Secretariat",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Pending Clearance",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 34,
        referenceNumber: "14483",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP022",
        employeeName: "Md. Manik Mia",
        designation: "Sr GM",
        department: "Chairman Secretariat",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Pending Clearance",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 35,
        referenceNumber: "14484",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP022",
        employeeName: "Md. Manik Mia",
        designation: "Sr GM",
        department: "Chairman Secretariat",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Completed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 36,
        referenceNumber: "14485",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP011",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Manager",
        department: "IP Trasmission",
        category: "IP Phone",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "In Process",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 37,
        referenceNumber: "14486",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP011",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Manager",
        department: "IP Trasmission",
        category: "UPS",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "In Process",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 38,
        referenceNumber: "14487",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP011",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Manager",
        department: "IP Trasmission",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Delayed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 39,
        referenceNumber: "14488",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP014",
        employeeName: "Nur Hossen",
        designation: "Assitant Manager",
        department: "Technology and Operations",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Upcoming Renewals",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },


    {
        sl: 40,
        referenceNumber: "14489",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP011",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Manager",
        department: "IP Trasmission",
        category: "Laptop LC-1",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Upcoming Renewals",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },


    {
        sl: 41,
        referenceNumber: "14490",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Kabir Uddin",
        designation: "Sr. Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Upcoming Renewals",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },


    {
        sl: 42,
        referenceNumber: "14491",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Kabir Uddin",
        designation: "Sr. Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Obsoleted",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },


    {
        sl: 42,
        referenceNumber: "14492",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Nahid Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Obsoleted",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },


    {
        sl: 42,
        referenceNumber: "14493",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Sharmin Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "User Ownership",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },


    {
        sl: 42,
        referenceNumber: "14494",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP010",
        employeeName: "Sharmin Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Tranferred to Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 43,
        referenceNumber: "14495",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP011",
        employeeName: "Sharmin Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Tranferred to Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 44,
        referenceNumber: "14496",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP012",
        employeeName: "Sharmin Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Tranferred to Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 45,
        referenceNumber: "14497",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP012",
        employeeName: "Sharmin Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Service Requrest",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    {
        sl: 46,
        referenceNumber: "14498",
        mrnNumber: "MR-2025-013",
        prNumber: "PR-2025-013",
        employeeId: "EMP013",
        employeeName: "Sharmin Islam",
        designation: "Manager",
        department: "HR",
        category: "Keyboard",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Service Requrest",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
        remarks: "Pending Clearance",
    },

    // ... more rows
];
