

/**
 * Temporary static data
 * Later replace with database API
 */

//services/ → handles fetching, mock data, API calls, business logic


//services/serviceRequestService.ts

//this functions (serviceRequestedDevices) is conncected with routing page  : //app/api/reports/service/route.ts


import { ServiceRequest } from "@/models/ServiceRequest";

export const serviceRequestedDevices: ServiceRequest[] = [
    {
        sl: 1,
        referenceNumber: "14451",
        employeeId: "02-0221",
        employeeName: "Md. Jalilur Rahman Hawlader",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620A",
        deviceType: "Permanent",
        status: "Expired",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "ruhul",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },

    {
        sl: 2,
        referenceNumber: "14452",
        employeeId: "02-0222",
        employeeName: "Md. Tauhid Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620B",
        deviceType: "Permanent",
        status: "Open",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "ruhul",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 3,
        referenceNumber: "14453",
        employeeId: "02-0223",
        employeeName: "Jamil Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620C",
        deviceType: "Permanent",
        status: "Closed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "ruhul",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },

    {
        sl: 4,
        referenceNumber: "14454",
        employeeId: "02-0224",
        employeeName: "Md. Manik Mia",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620D",
        deviceType: "Permanent",
        status: "Recovered",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 5,
        referenceNumber: "14455",
        employeeId: "02-0225",
        employeeName: "Md. Karim Uddin",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620E",
        deviceType: "Permanent",
        status: "Recovered",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 6,
        referenceNumber: "14456",
        employeeId: "02-0226",
        employeeName: "Md. Nzimul Islam",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620F",
        deviceType: "Permanent",
        status: "Closed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 7,
        referenceNumber: "14457",
        employeeId: "02-0227",
        employeeName: "Md. Jamil Uddin",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Recovered",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },

    {
        sl: 8,
        referenceNumber: "14458",
        employeeId: "02-0228",
        employeeName: "Md. Zaman Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Recovered",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },

    {
        sl: 9,
        referenceNumber: "14459",
        employeeId: "02-0229",
        employeeName: "Mohammad Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 10,
        referenceNumber: "14460",
        employeeId: "02-0230",
        employeeName: "Md. Zobayar Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Vendor",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },

    {
        sl: 11,
        referenceNumber: "14461",
        employeeId: "02-0230",
        employeeName: "Md. Nayem Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Requests",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 12,
        referenceNumber: "14462",
        employeeId: "02-0230",
        employeeName: "Md. Nizam Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Closed",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    {
        sl: 13,
        referenceNumber: "14462",
        employeeId: "02-0230",
        employeeName: "Md. Tareque Ali",
        designation: "Chief Technician",
        department: "Technology and Operations",
        category: "Mouse",
        deviceSl: "nosn54643d",
        model: "OP-620G",
        deviceType: "Permanent",
        status: "Requests",
        userUsageDuration: "2 hours 26 minutes",
        deviceAge: "3 months 30 days",
        warranty: "8 months left",
        vendor: "Famous Technologies",
        assignedBy: "nur",
        assignedDate: "2026-01-15 12:56:55",
        purchaseDate: "2025-09-16",
    },
    // ... more rows
];


// Optional helper (recommended)
export async function getServiceRequests(): Promise<ServiceRequest[]> {
    return serviceRequestedDevices;
}